version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: maze-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - maze-data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/maze_app.db
      - DEBUG=True
    networks:
      - maze-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: maze-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
    networks:
      - maze-network
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  maze-data:
    driver: local

networks:
  maze-network:
    driver: bridge